"""Repository-wide external dependency discovery (M5.2 / M5.6).

``discover_dependencies(root)`` is deterministic, offline and read-only:

1. enumerate files safely (:mod:`patchfrog.dependencies.files` -- secret
   stores are never opened);
2. parse manifests/lockfiles and local OpenAPI specs;
3. scan Python (``ast``) and JS/TS (lexical) sources once each;
4. let every adapter turn observations into evidence and evidence into
   dependencies;
5. attach enclosing symbols to usage sites -- Python through the same
   tree-sitter parser the repository index uses (so qualified names line
   up with Change/Contract Intelligence), JS/TS through a lexical span
   scan.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path, PurePosixPath
from types import MappingProxyType

from patchfrog.dependencies.adapters import (
    KNOWN_PROVIDER_SPECS,
    DependencyDraft,
    DependencyProviderAdapter,
    FileScanContext,
    PackageIndex,
    default_provider_adapters,
)
from patchfrog.dependencies.domain import (
    USAGE_EVIDENCE,
    ContractSource,
    ContractSourceType,
    DependencyContract,
    DependencyInventory,
    DependencyProvider,
    DependencyUsageSite,
    DependencyVersion,
    DetectionConfidence,
    DiscoveryEvidence,
    Ecosystem,
    EvidenceType,
    ExternalDependency,
    ExternalDependencyKind,
    PackageDeclaration,
    PackageResolution,
)
from patchfrog.dependencies.files import (
    MAX_OPENAPI_FILE_BYTES,
    RepositoryFile,
    WalkStats,
    iter_repository_files,
    read_text,
)
from patchfrog.dependencies.manifests import (
    is_lockfile,
    is_manifest,
    parse_lockfile,
    parse_manifest,
)
from patchfrog.dependencies.openapi import fingerprint_normalized, load_spec, looks_like_spec_path
from patchfrog.dependencies.openapi_adapter import LocalSpec, OpenAPIAdapter
from patchfrog.dependencies.scan import (
    ObservationKind,
    javascript_symbol_spans,
    scan_javascript,
    scan_python,
)
from patchfrog.domain.code import Language
from patchfrog.parsing.registry import default_registry

_PY_SUFFIXES = (".py", ".pyi")
_JS_SUFFIXES = (".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts")
_GENERATED_CLIENT_MARKER = "generated by openapi generator"
_USAGE_CONFIDENCE = {
    EvidenceType.IMPORT: DetectionConfidence.HIGH,
    EvidenceType.SDK_CONSTRUCTOR: DetectionConfidence.HIGH,
    EvidenceType.SDK_CALL: DetectionConfidence.HIGH,
    EvidenceType.HTTP_ENDPOINT: DetectionConfidence.HIGH,
    EvidenceType.OPENAPI_PATH_REFERENCE: DetectionConfidence.MEDIUM,
    EvidenceType.GENERATED_CLIENT: DetectionConfidence.MEDIUM,
    EvidenceType.ENV_VAR_NAME: DetectionConfidence.LOW,
}


def _local_python_modules(paths: Sequence[str]) -> frozenset[str]:
    """Top-level importable names the repository defines itself (a
    top-level ``x.py``, a top-level package directory, or the same one
    level below ``src/``/``lib/``)."""

    names: set[str] = set()
    for path in paths:
        parts = PurePosixPath(path).parts
        if parts and parts[0] in {"src", "lib"} and len(parts) > 1:
            parts = parts[1:]
        head = parts[0][:-3] if len(parts) == 1 and parts[0].endswith(".py") else parts[0]
        if len(parts) >= 1 and head.isidentifier():
            names.add(head)
    return frozenset(names)


class _SymbolLocator:
    def __init__(self) -> None:
        self._python = default_registry().get(Language.PYTHON)
        self._spans: dict[str, list[tuple[str, int, int]]] = {}

    def add_python(self, path: str, text: str) -> None:
        if self._python is None:
            return
        parsed = self._python.parse_file(relative_path=path, content=text.encode("utf-8"))
        self._spans[path] = [(s.qualified_name, s.span.start_line, s.span.end_line) for s in parsed.symbols]

    def add_javascript(self, path: str, text: str) -> None:
        self._spans[path] = javascript_symbol_spans(text)

    def symbol_at(self, path: str, line: int | None) -> str | None:
        if line is None:
            return None
        containing = [s for s in self._spans.get(path, ()) if s[1] <= line <= s[2]]
        if not containing:
            return None
        return min(containing, key=lambda s: (s[2] - s[1], -s[1]))[0]


def discover_dependencies(
    root: Path,
    *,
    repository: str | None = None,
    commit_sha: str | None = None,
    adapters: Sequence[DependencyProviderAdapter] | None = None,
) -> DependencyInventory:
    stats = WalkStats()
    files: list[RepositoryFile] = list(iter_repository_files(root, stats))
    all_paths = [f.relative_path for f in files]
    local_modules = _local_python_modules([p for p in all_paths if p.endswith(".py")])

    declarations: list[PackageDeclaration] = []
    resolutions: list[PackageResolution] = []
    specs: list[LocalSpec] = []
    generated_markers: list[str] = []
    sources: list[tuple[RepositoryFile, str, str]] = []

    for file in files:
        path = file.relative_path
        if is_manifest(path) or is_lockfile(path):
            text = read_text(file, max_bytes=MAX_OPENAPI_FILE_BYTES)
            if text is not None:
                if is_manifest(path):
                    declarations.extend(parse_manifest(path, text))
                else:
                    resolutions.extend(parse_lockfile(path, text))
            continue
        if path.endswith((".yaml", ".yml", ".json")):
            if looks_like_spec_path(path) or path.endswith((".yaml", ".yml")):
                text = read_text(file, max_bytes=MAX_OPENAPI_FILE_BYTES)
                document = load_spec(text) if text is not None and _mentions_spec_version(text) else None
                if document is not None:
                    specs.append(LocalSpec(path=path, document=document))
            continue
        if PurePosixPath(path).parent.name == ".openapi-generator" and PurePosixPath(path).name == "VERSION":
            generated_markers.append(str(PurePosixPath(path).parent.parent) or ".")
            continue
        if path.endswith(_PY_SUFFIXES) or path.endswith(_JS_SUFFIXES):
            text = read_text(file)
            if text is None:
                continue
            language = "python" if path.endswith(_PY_SUFFIXES) else "javascript"
            if _GENERATED_CLIENT_MARKER in text[:600].lower():
                generated_markers.append(path)
            sources.append((file, text, language))

    provider_adapters: list[DependencyProviderAdapter] = list(adapters) if adapters is not None else list(
        default_provider_adapters()
    )
    provider_adapters.append(OpenAPIAdapter(specs, generated_client_paths=sorted(set(generated_markers))))
    tracked = frozenset().union(*(a.tracked_modules() for a in provider_adapters))

    locator = _SymbolLocator()
    evidence: list[DiscoveryEvidence] = []
    imports: list[tuple[str, str, int]] = []  # (path, module, line) for generic packages
    for file, text, language in sources:
        if language == "python":
            observations = scan_python(text, tracked_modules=tracked)
            locator.add_python(file.relative_path, text)
        else:
            observations = scan_javascript(text, tracked_modules=tracked)
            locator.add_javascript(file.relative_path, text)
        context = FileScanContext(
            path=file.relative_path,
            language=language,
            observations=tuple(observations),
            local_python_modules=local_modules,
        )
        for adapter in provider_adapters:
            evidence.extend(adapter.discover_usage(context))
        imports.extend(
            (file.relative_path, o.subject, o.line) for o in observations if o.kind is ObservationKind.IMPORT
        )

    packages = PackageIndex(declarations=tuple(declarations), resolutions=tuple(resolutions))
    drafts: list[DependencyDraft] = []
    for adapter in provider_adapters:
        key = adapter.provider.key
        own = [
            e for e in evidence
            if e.provider_key == key or (key == "openapi" and e.provider_key.startswith("openapi:"))
        ]
        drafts.extend(adapter.normalize_dependency(own, packages))
    drafts.extend(_generic_package_drafts(packages, imports, local_modules))

    dependencies = tuple(
        sorted((_finalize(d, locator) for d in drafts), key=lambda d: (d.kind is ExternalDependencyKind.PACKAGE, d.key))
    )
    return DependencyInventory(
        repository=repository or root.resolve().name,
        commit_sha=commit_sha,
        dependencies=dependencies,
        files_scanned=stats.files_scanned,
        secret_store_files_skipped=stats.secret_store_files_skipped,
    )


def _mentions_spec_version(text: str) -> bool:
    head = text[:4096]
    return "openapi" in head or "swagger" in head


def _claimed_packages() -> set[tuple[Ecosystem, str]]:
    return {(eco, name) for spec in KNOWN_PROVIDER_SPECS for eco, names in spec.packages.items() for name in names}


def _generic_package_drafts(
    packages: PackageIndex, imports: Sequence[tuple[str, str, int]], local_modules: frozenset[str]
) -> list[DependencyDraft]:
    """Declared packages no provider adapter claims -- dependencies too,
    but plain packages: evidence is the declaration plus imports of the
    package's (conventional) import name."""

    claimed = _claimed_packages()
    seen: set[tuple[Ecosystem, str]] = set()
    drafts: list[DependencyDraft] = []
    for declaration in packages.declarations:
        ident = (declaration.ecosystem, declaration.name)
        if ident in claimed or ident in seen:
            continue
        seen.add(ident)
        key = f"package:{declaration.ecosystem.value}:{declaration.name}"
        evidence = [DiscoveryEvidence(key, EvidenceType.MANIFEST_DECLARATION, declaration.manifest_path,
                                      declaration.line, declaration.name)]
        resolution = packages.resolved(declaration.ecosystem, declaration.name)
        if resolution is not None:
            evidence.append(DiscoveryEvidence(key, EvidenceType.LOCKFILE_RESOLUTION, resolution.lockfile_path, None,
                                              resolution.name))
        if declaration.ecosystem is Ecosystem.PYPI:
            module = declaration.name.replace("-", "_").lower()
            if module not in local_modules:
                evidence += [
                    DiscoveryEvidence(key, EvidenceType.IMPORT, path, line, name)
                    for path, name, line in imports
                    if path.endswith(_PY_SUFFIXES) and name.split(".")[0].lower() == module
                ]
        elif declaration.ecosystem is Ecosystem.NPM:
            evidence += [
                DiscoveryEvidence(key, EvidenceType.IMPORT, path, line, name)
                for path, name, line in imports
                if path.endswith(_JS_SUFFIXES) and (name == declaration.name or name.startswith(f"{declaration.name}/"))
            ]
        version = DependencyVersion(
            declared=declaration.spec,
            resolved=resolution.version if resolution else None,
            declared_in=declaration.manifest_path,
            resolved_in=resolution.lockfile_path if resolution else None,
        )
        normalized = {
            "ecosystem": declaration.ecosystem.value,
            "package": declaration.name,
            "declared": version.declared,
            "resolved": version.resolved,
        }
        imported = any(e.evidence_type is EvidenceType.IMPORT for e in evidence)
        drafts.append(
            DependencyDraft(
                key=key,
                provider=DependencyProvider(key=declaration.name, display_name=declaration.name),
                kind=ExternalDependencyKind.PACKAGE,
                ecosystem=declaration.ecosystem,
                package_name=declaration.name,
                version=version,
                evidence=tuple(evidence),
                confidence=DetectionConfidence.HIGH if imported else DetectionConfidence.MEDIUM,
                contract=DependencyContract(
                    source=ContractSource(
                        ContractSourceType.PACKAGE_MANIFEST,
                        f"{declaration.ecosystem.value}:{declaration.name}@{version.resolved or version.declared or 'unversioned'}",
                    ),
                    fingerprint=fingerprint_normalized(normalized),
                    normalized=normalized,
                ),
                metadata=MappingProxyType({"relationship": "declared_package"}),
            )
        )
    return drafts


def _finalize(draft: DependencyDraft, locator: _SymbolLocator) -> ExternalDependency:
    sites = {
        DependencyUsageSite(
            file_path=e.file_path,
            line=e.line,
            symbol=locator.symbol_at(e.file_path, e.line),
            evidence_type=e.evidence_type,
            token=e.token,
            confidence=_USAGE_CONFIDENCE.get(e.evidence_type, DetectionConfidence.MEDIUM),
        )
        for e in draft.evidence
        if e.evidence_type in USAGE_EVIDENCE
    }
    return ExternalDependency(
        key=draft.key,
        provider=draft.provider,
        kind=draft.kind,
        ecosystem=draft.ecosystem,
        package_name=draft.package_name,
        version=draft.version,
        usage_sites=tuple(sorted(sites, key=lambda s: (s.file_path, s.line or 0, s.evidence_type.value, s.token))),
        evidence=draft.evidence,
        confidence=draft.confidence,
        contract=draft.contract,
        metadata=draft.metadata,
    )


__all__ = ["discover_dependencies"]
