"""Deterministic file inventory for a repository snapshot.

Uses ``git ls-files`` so only content actually tracked by git is
considered — this is what respects ``.gitignore`` "for free" and avoids
ever indexing local secrets, build artifacts, or virtualenvs, without
reimplementing gitignore parsing. A defensive vendor/build-directory
denylist and size/binary checks apply on top, in case such paths were
ever accidentally committed.
"""

from __future__ import annotations

import re
from pathlib import PurePosixPath

from patchfrog.indexing.models import FileInventoryEntry
from patchfrog.parsing.base import content_hash
from patchfrog.parsing.detect import detect_language
from patchfrog.repository.git import run_git
from patchfrog.repository.snapshot import RepositorySnapshot

MAX_FILE_SIZE_BYTES = 2 * 1024 * 1024  # 2 MiB — larger files are skipped, not truncated.

_DENYLISTED_DIR_NAMES = frozenset(
    {
        ".git",
        "node_modules",
        ".venv",
        "venv",
        "env",
        "dist",
        "build",
        "target",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        "vendor",
        "third_party",
        "thirdparty",
    }
)

_TEST_PATH_RE = re.compile(
    r"(^|/)(tests?)(/|$)|(^|[_/-])test[_-]|[_-]test(\.[A-Za-z0-9]+)?$", re.IGNORECASE
)

_GENERATED_MARKERS = (
    b"do not edit",
    b"auto-generated",
    b"autogenerated",
    b"@generated",
    b"generated by",
    b"this file is generated",
)
_GENERATED_SNIFF_BYTES = 512


def build_inventory(snapshot: RepositorySnapshot) -> list[FileInventoryEntry]:
    """Build the file inventory for a repository snapshot."""

    entries: list[FileInventoryEntry] = []
    for relative_path, blob_sha in _tracked_files_with_blob_sha(snapshot):
        if _is_denylisted(relative_path):
            continue

        # Checked *before* resolving: a git-tracked symlink (mode 120000)
        # must never be followed, whether it points inside the repo or
        # escapes it. Checking the unresolved path first also means a
        # symlink deliberately crafted to escape the checkout root (e.g.
        # `../../../etc/passwd`) is skipped here rather than reaching
        # `resolve_path`'s traversal guard at all.
        raw_path = snapshot.root_path / relative_path
        if raw_path.is_symlink():
            continue

        try:
            absolute_path = snapshot.resolve_path(relative_path)
        except ValueError:
            # Defense in depth: some other non-symlink path escaped the
            # checkout root. A malicious/malformed repository must not be
            # able to crash the whole indexing run over one bad path.
            continue
        if not absolute_path.is_file():
            continue  # gitlinks (submodules), non-regular files

        try:
            size_bytes = absolute_path.stat().st_size
        except OSError:
            continue
        if size_bytes > MAX_FILE_SIZE_BYTES:
            continue

        try:
            data = absolute_path.read_bytes()
        except OSError:
            continue
        if _looks_binary(data):
            continue

        language = detect_language(relative_path=relative_path, content=data)

        entries.append(
            FileInventoryEntry(
                relative_path=relative_path,
                language=language,
                size_bytes=size_bytes,
                content_hash=content_hash(data),
                git_blob_sha=blob_sha,
                is_test=is_test_path(relative_path),
                is_generated=_looks_generated(data),
            )
        )

    return entries


def is_test_path(relative_path: str) -> bool:
    """Conservative, language-agnostic "does this look like a test file" check."""

    return bool(_TEST_PATH_RE.search(relative_path))


def _tracked_files_with_blob_sha(snapshot: RepositorySnapshot) -> list[tuple[str, str]]:
    output = run_git(["-C", str(snapshot.root_path), "ls-files", "-s", "-z"])
    results: list[tuple[str, str]] = []
    for record in output.split("\0"):
        if not record:
            continue
        meta, _, path = record.partition("\t")
        parts = meta.split()
        if len(parts) < 2:
            continue
        blob_sha = parts[1]
        results.append((path, blob_sha))
    return results


def _is_denylisted(relative_path: str) -> bool:
    return any(part in _DENYLISTED_DIR_NAMES for part in PurePosixPath(relative_path).parts[:-1])


def _looks_binary(data: bytes) -> bool:
    return b"\x00" in data[:8192]


def _looks_generated(data: bytes) -> bool:
    sample = data[:_GENERATED_SNIFF_BYTES].lower()
    return any(marker in sample for marker in _GENERATED_MARKERS)
